export const COUNTRY_FLAGS: Record<string, string> = {
  // Europe
  "Albania": "🇦🇱", "Andorra": "🇦🇩", "Austria": "🇦🇹", "Belarus": "🇧🇾",
  "Belgium": "🇧🇪", "Bosnia and Herzegovina": "🇧🇦", "Bulgaria": "🇧🇬",
  "Croatia": "🇭🇷", "Cyprus": "🇨🇾", "Czech Republic": "🇨🇿", "Czechia": "🇨🇿",
  "Denmark": "🇩🇰", "Estonia": "🇪🇪", "Finland": "🇫🇮", "France": "🇫🇷",
  "Germany": "🇩🇪", "Greece": "🇬🇷", "Hungary": "🇭🇺", "Iceland": "🇮🇸",
  "Ireland": "🇮🇪", "Italy": "🇮🇹", "Kosovo": "🇽🇰", "Latvia": "🇱🇻",
  "Liechtenstein": "🇱🇮", "Lithuania": "🇱🇹", "Luxembourg": "🇱🇺",
  "Malta": "🇲🇹", "Moldova": "🇲🇩", "Monaco": "🇲🇨", "Montenegro": "🇲🇪",
  "Netherlands": "🇳🇱", "North Macedonia": "🇲🇰", "Norway": "🇳🇴",
  "Poland": "🇵🇱", "Portugal": "🇵🇹", "Romania": "🇷🇴", "Russia": "🇷🇺",
  "San Marino": "🇸🇲", "Serbia": "🇷🇸", "Slovakia": "🇸🇰", "Slovenia": "🇸🇮",
  "Spain": "🇪🇸", "Sweden": "🇸🇪", "Switzerland": "🇨🇭", "Turkey": "🇹🇷",
  "Ukraine": "🇺🇦", "United Kingdom": "🇬🇧", "Vatican City": "🇻🇦",
  // Americas
  "Argentina": "🇦🇷", "Belize": "🇧🇿", "Bolivia": "🇧🇴", "Brazil": "🇧🇷",
  "Canada": "🇨🇦", "Chile": "🇨🇱", "Colombia": "🇨🇴", "Costa Rica": "🇨🇷",
  "Cuba": "🇨🇺", "Dominican Republic": "🇩🇴", "Ecuador": "🇪🇨",
  "El Salvador": "🇸🇻", "Guatemala": "🇬🇹", "Haiti": "🇭🇹",
  "Honduras": "🇭🇳", "Jamaica": "🇯🇲", "Mexico": "🇲🇽", "Nicaragua": "🇳🇮",
  "Panama": "🇵🇦", "Paraguay": "🇵🇾", "Peru": "🇵🇪",
  "Puerto Rico": "🇵🇷", "Trinidad and Tobago": "🇹🇹", "United States": "🇺🇸",
  "Uruguay": "🇺🇾", "Venezuela": "🇻🇪",
  // Asia
  "Afghanistan": "🇦🇫", "Armenia": "🇦🇲", "Azerbaijan": "🇦🇿",
  "Bahrain": "🇧🇭", "Bangladesh": "🇧🇩", "Bhutan": "🇧🇹", "Brunei": "🇧🇳",
  "Cambodia": "🇰🇭", "China": "🇨🇳", "Georgia": "🇬🇪", "Hong Kong": "🇭🇰",
  "India": "🇮🇳", "Indonesia": "🇮🇩", "Iran": "🇮🇷", "Iraq": "🇮🇶",
  "Israel": "🇮🇱", "Japan": "🇯🇵", "Jordan": "🇯🇴", "Kazakhstan": "🇰🇿",
  "Kuwait": "🇰🇼", "Kyrgyzstan": "🇰🇬", "Laos": "🇱🇦", "Lebanon": "🇱🇧",
  "Macau": "🇲🇴", "Malaysia": "🇲🇾", "Maldives": "🇲🇻", "Mongolia": "🇲🇳",
  "Myanmar": "🇲🇲", "Nepal": "🇳🇵", "North Korea": "🇰🇵", "Oman": "🇴🇲",
  "Pakistan": "🇵🇰", "Palestine": "🇵🇸", "Philippines": "🇵🇭", "Qatar": "🇶🇦",
  "Saudi Arabia": "🇸🇦", "Singapore": "🇸🇬", "South Korea": "🇰🇷",
  "Sri Lanka": "🇱🇰", "Syria": "🇸🇾", "Taiwan": "🇹🇼", "Tajikistan": "🇹🇯",
  "Thailand": "🇹🇭", "Timor-Leste": "🇹🇱", "Turkmenistan": "🇹🇲",
  "United Arab Emirates": "🇦🇪", "Uzbekistan": "🇺🇿", "Vietnam": "🇻🇳",
  "Yemen": "🇾🇪",
  // Africa
  "Algeria": "🇩🇿", "Angola": "🇦🇴", "Benin": "🇧🇯", "Botswana": "🇧🇼",
  "Burkina Faso": "🇧🇫", "Burundi": "🇧🇮", "Cameroon": "🇨🇲",
  "Cape Verde": "🇨🇻", "Central African Republic": "🇨🇫", "Chad": "🇹🇩",
  "Comoros": "🇰🇲", "Congo": "🇨🇬", "Democratic Republic of the Congo": "🇨🇩",
  "Djibouti": "🇩🇯", "Egypt": "🇪🇬", "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷", "Eswatini": "🇸🇿", "Ethiopia": "🇪🇹", "Gabon": "🇬🇦",
  "Gambia": "🇬🇲", "Ghana": "🇬🇭", "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼", "Ivory Coast": "🇨🇮", "Kenya": "🇰🇪",
  "Lesotho": "🇱🇸", "Liberia": "🇱🇷", "Libya": "🇱🇾",
  "Madagascar": "🇲🇬", "Malawi": "🇲🇼", "Mali": "🇲🇱", "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺", "Morocco": "🇲🇦", "Mozambique": "🇲🇿", "Namibia": "🇳🇦",
  "Niger": "🇳🇪", "Nigeria": "🇳🇬", "Rwanda": "🇷🇼",
  "São Tomé and Príncipe": "🇸🇹", "Senegal": "🇸🇳", "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱", "Somalia": "🇸🇴", "South Africa": "🇿🇦",
  "South Sudan": "🇸🇸", "Sudan": "🇸🇩", "Tanzania": "🇹🇿", "Togo": "🇹🇬",
  "Tunisia": "🇹🇳", "Uganda": "🇺🇬", "Zambia": "🇿🇲", "Zimbabwe": "🇿🇼",
  // Oceania
  "Australia": "🇦🇺", "Fiji": "🇫🇯", "Kiribati": "🇰🇮",
  "Marshall Islands": "🇲🇭", "Micronesia": "🇫🇲", "Nauru": "🇳🇷",
  "New Zealand": "🇳🇿", "Palau": "🇵🇼", "Papua New Guinea": "🇵🇬",
  "Samoa": "🇼🇸", "Solomon Islands": "🇸🇧", "Tonga": "🇹🇴",
  "Tuvalu": "🇹🇻", "Vanuatu": "🇻🇺",
};

export function getFlag(country: string): string {
  return COUNTRY_FLAGS[country] ?? "";
}
